[package]
name = "bloom_filter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.10.8"
generic-array = "1.0.0"
bit-vec = "0.6"